# Generated by Django 4.2.30 on 2026-09-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Razorpay event.id (globally unique).', max_length=64, unique=True)),
                ('event_type', models.CharField(help_text='Razorpay event.event (e.g. order.paid).', max_length=80)),
                ('payload', models.JSONField(help_text='Full Razorpay event payload.')),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed'), ('signature_invalid', 'Signature invalid')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type'], name='payments_ra_event_t_4b92f9_idx'), models.Index(fields=['status'], name='payments_ra_status_baad49_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(blank=True, help_text='Razorpay payment_link.id', max_length=64)),
                ('short_url', models.URLField(blank=True, help_text='Public URL donors click to pay.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('partial', 'Partially paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links', to='core.donation')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links', to='core.donor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
